name: Build

on:
  push:
  workflow_call:

jobs:
  shared:
    name: Shared
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: shared/package-lock.json
      - name: Install deps
        working-directory: ./shared
        run: npm ci
      - name: Build
        working-directory: ./shared
        run: npm run build
      - name: Lint
        working-directory: ./shared
        run: npm run lint

  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - name: Install deps
        working-directory: ./backend
        run: npm ci
      - name: Build
        working-directory: ./backend
        run: npm run build
      - name: Test
        working-directory: ./backend
        run: npm run test
      - name: Lint
        working-directory: ./backend
        run: npm run lint

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        working-directory: ./frontend
        run: npm ci
      - name: Build
        working-directory: ./frontend
        run: npm run build
      - name: Lint
        working-directory: ./frontend
        run: npm run lint
